---

- hosts: all
  tasks:
    - name: Install latest nginx
      ansible.builtin.apt:
        name: nginx
        state: latest

    - name: Enable the nginx service
      ansible.builtin.service:
        name: nginx
        enabled: yes
        state: started
